name: turbo_routing
description: Routing abstraction layer over go_router for Flutter.
version: 1.1.0
homepage: https://github.com/appboypov/turbo_routing
repository: https://github.com/appboypov/turbo_routing

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  turbo_widgets: ^1.0.0
  go_router: ^15.0.0
  get_it: ^8.0.0
  turbo_notifiers: ^1.0.0
  turbolytics: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
